kind: pipeline
name: Audit, Build, Publish and Deploy

steps:
  - name: Audit
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build --target test --tag devpies/client-api:test ./api

  - name: Github Release
    image: devpies/github-release-drone:1.0.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

  - name: Build & Publish
    image: docker:git
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      BACKEND: https://api.devpie.io/api/v1
      FRONTEND: https://client.devpie.io
      API_NAMESPACE: /api/v1
      DOCKER_USER:
        from_secret: registry_user
      DOCKER_PASS:
        from_secret: registry_pass
    commands:
      - docker login -u $DOCKER_USER  -p $DOCKER_PASS
      - >
        docker build --target prod
        --build-arg backend=$BACKEND
        --build-arg frontend=$FRONTEND
        --build-arg api_namespace=$API_NAMESPACE
        --tag devpies/client-api:$(git describe --tags --abbrev=0 | tr -d "v") ./api
      - docker push devpies/client-api:$(git describe --tags --abbrev=0 | tr -d "v")

  - name: Redeploy
    image: docker:git
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      PORTAINER_WEBHOOK:
        from_secret: portainer_webhook
    commands:
      - >
        docker run --rm
        -e PLUGIN_URLS=$PORTAINER_WEBHOOK?tag=$(git describe --tags --abbrev=0 | tr -d "v")
        plugins/webhook

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
  event:
    - push
